source 'https://rubygems.org'

gem 'hobby'
gem 'hobby-json'
gem 'redis'
gem 'suppress_output'
gem 'slim'
gem 'sass'

gem 'rspec'
gem 'rspec-power_assert'
gem 'puma'
gem 'excon'

gem 'pry'
gem 'awesome_print'
